# Generated by Django 5.1.2 on 2024-10-31 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_tittle_product_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('region', models.CharField(choices=[('GOASO', 'AHAFO'), ('KUMASI', 'ASHANTI'), ('TECHIMAN', 'BONO EAST'), ('SUNYANI', 'BRONG AHAFO'), ('CAPE COAST', 'CENTRAL'), ('KOFORIDUA', 'EASTERN'), ('ACCRA', 'GREATER ACCRA'), ('NALERIGU', 'NORTH EAST'), ('TAMALE', 'NORTHERN'), ('DAMBAI', 'OTI'), ('DAMANGO', 'SAVANNAH'), ('BOLGATANGA', 'UPPER EAST'), ('WA', 'UPPER WEST'), ('TAKORADI', 'WESTERN'), ('SEFWI WIASO', 'WESTERN NORTH'), ('HO', 'VOLTA')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
